# ======================================================== #
#                                                          #
#     Edit the information in this configuration file      #
#                                                          #
# ======================================================== #

# ====== Info applying to the whole variant library ====== #
organism: Severe acute respiratory syndrome coronavirus 2
strain: KP.3.1.1
isolation_source: HEK-293T-medium-ACE2
collection_date: 2025
geographic_location: 'USA: Washington'
sample_type: DNA amplicon

# ======== Info for Illumina barcodes BioSamples ======== #
barcode_runs: 
  
  # Path to the barcoded runs csv file that will go into the BioSample
  file_path: ../data/barcode_runs.csv
  
  # Edit this data that goes into the SRA metadata table for the BioSample
  accession: SAMN50583693
  sample_id_columns: [sample]
  title_prefix: KP.3.1.1 spike DMS Illumina barcode sequencing for infant sera  
  description: Illumina barcode sequencing KP.3.1.1 spike
  strategy: AMPLICON
  source: SYNTHETIC
  selection: PCR
  layout: single
  platform: ILLUMINA
  model: Illumina NovaSeq X

  # Meaningful BioSample specific folder name for FTP upload
  ftp_subfolder: KP.3.1.1_spike_infant_sera_DMS_barcodes

# =========== Info for uploading to SRA via FTP =========== #
# These come from the SRA FTP upload instructions.
ftp_username: subftp
ftp_account_folder: uploads/bdadonaite_gmail.com_siPEAzaM

# ========== Info for PacBio library BioSample ========== #
pacbio_runs:
  
  # Path to the pacbio runs that will be included in the BioSample
  file_path: ../data/PacBio_runs.csv
 
  # This data goes into the SRA metadata table
  accession: SAMN50583930
  title_prefix: PacBio CCSs linking variants to barcodes for SARS-CoV-2 KP.3.1.1 full spike deep mutational scanning
  description: genomes from infection with VSV-G pseuodotyped libraries
  strategy: Synthetic-Long-Read
  source: SYNTHETIC
  selection: Restriction Digest
  layout: single
  platform: PACBIO_SMRT
  model: Sequel II

  # Meaningful BioSample specific folder name for FTP upload
  ftp_subfolder: Omicron_KP311_spike_DMS_pacbio_ccss